### ISSUE TITLE
Preferences for size of graphics

### ISSUE THREAD

**Issue by benjaoming** [benjaoming/rhythmbox-fullscreen#6]
Users should have an option to choose the fractional size of the display to use. This fraction is currently hardcoded through the enhancements of 509ea90.

 * [ ] A change in resolution only requires a relaunch of the fullscreen window.
 * [ ] Make it possible for users to manually specify the size in Preferences

**Comment by fossfreedom** [comment]
@benjaoming 

  not exactly as you may want - but the above commit basically removes the hard-coded 800x800 and 300x300 stuff and instead use the active monitor geometry.

BTW - you'll also a commit to resolve a RB3.2 issue and I've run through the code with pycharm code cleanup stuff.

**Comment by benjaoming** [comment]
Good to see you back! :)

Thanks for making a simple fix for a problem that perhaps I over complicated.

The PEP8 stuff is absolutely welcome, I wrote this code in Eclipse/PyDev back when code cleanup features were still sparse, hence all the PEP8 invalidness.

Perhaps a version bump in the [.plugin configuration](https://github.com/benjaoming/rhythmbox-fullscreen/blob/master/RhythmboxFullscreen.plugin) is a good idea?

**Comment by benjaoming** [comment]
Also tested and works on RB 3.0.2 :+1:

**Comment by fossfreedom** [comment]
good point!
