### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by etsnyman** [benjaoming/rhythmbox-fullscreen#7]
This plugin simply does not work in any way with Rhythmbox 3.1 on Ubuntu. No button, F12 does not work, no View>Fullscreen, nothing.

**Comment by fossfreedom** [comment]
type rhythmbox from a terminal

enable the plugin and choose view--> fullscreen

what messages do you see being outputted in the terminal?

**Comment by etsnyman** [comment]
Ok. If I run Rhythmbox from the commandline, by typing "rhythmbox" and pressing Enter, I see the option and it works. If I run it normally (from Gnome Shell) then it doesn't work and there is no option to view fullscreen...

**Comment by fossfreedom** [comment]
very strange

when you run rhythmbox normally from activities - is the full-screen plugin enabled via the plugins window?

Is this a stock ubuntu install or have you got a manually compiled rhythmbox - or something different with your installation.

what version of ubuntu are you referring to - 15.04?

**Comment by etsnyman** [comment]
1. "is the full-screen plugin enabled via the plugins window?"
> Yes, it is, but there is no option under the View menu.

2. "Is this a stock ubuntu install or have you got a manually compiled rhythmbox - or something different with your installation."
> Stock Ubuntu Gnome 15.04. Rhythmbox was pre-installed.

**Comment by benjaoming** [comment]
What about other plugins? Do they work?

**Comment by etsnyman** [comment]
They work no problem.

**Comment by fossfreedom** [comment]
hmm - managed to reproduce this on ubuntu 14.04 with gnome-shell desktop installed.

This problem appears to be very specific to gnome-shell - no other desktop environment is affected - e.g. unity/xfce/lxde all work for me.

No idea how to debug though - it works as you have said if you launch rhythmbox via a terminal.

**Comment by benjaoming** [comment]
Could there be some kind of environment var missing in Gnome Shell or set wrongly? For instance the path to local plugins, in case this is a local plugin installation?

Try this:

1. Rename /usr/bin/rhythmbox to /usr/bin/rhythmbox_orig
2. `sudo nano /usr/bin/rhythmbox`

    #!/bin/bash
    echo "`env`" > /tmp/gnome_shell_env.dump
    /usr/bin/rhythmbox_orig -D RhythmboxFullscreen 2>&1 > /tmp/rb_debug.out

Try comparing the dumped env in `/tmp/gnome_shell_env.dump` with what you get by running just `env` in the working terminal. Also check if there are errors in `/tmp/rb_debug.out`.

**Comment by fossfreedom** [comment]
should be fixed now.

@benjaoming - bizarre commit as you can see - by just moving that monitor calc code this fixes the menu issue.  Go figure!

@etsnyman - please can you test by installing the latest code.

once confirmed I'll bump the minor version number

**Comment by etsnyman** [comment]
@fossfreedom It seems to work perfectly now. Thanks!
